# Generated by Django 4.2.5 on 2023-09-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Client Logo')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('sub_text', models.TextField(verbose_name='Sub Text')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Image')),
                ('role', models.TextField(verbose_name='Role')),
                ('collaborators', models.TextField(verbose_name='Collaborators')),
                ('deliverables', models.TextField(verbose_name='Deliverables')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Determine whether the case study is going to be displayed on the home page or not.', null=True, verbose_name='Is Active')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.CreateModel(
            name='DribbleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dribbles/', verbose_name='Image')),
                ('url', models.URLField(verbose_name='Link')),
                ('alt', models.CharField(help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=500, verbose_name='Alternative (Alt)')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Determine whether the dribble work is going to be displayed on the home page or not.', null=True, verbose_name='Is Active')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Dribble Work',
                'verbose_name_plural': 'Dribble Works',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
        migrations.CreateModel(
            name='CaseStudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('sub_text', models.TextField(verbose_name='Sub Text')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Image')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Determine whether the case study section is going to be displayed on the home page or not.', null=True, verbose_name='Is Active')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='info.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Section',
                'verbose_name_plural': 'Case Study Sections',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
    ]
